### ISSUE TITLE
Add a way to deploy grafana dashboard the gitops way

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops-profile-examples#59]
We could use a config map to define dashboards and a grafana side cart to put the dashboards as a file into the grafana pod.

Something like this :
https://medium.com/riskified-technology/consistent-monitoring-the-gitops-way-1d481e9965c9

**Comment by darrylweaver** [comment]
There is a way to do this and I was going to create a profile for it anyway, so we get the flux dashboards in leaf clusters.
https://app.asana.com/0/1200931249282497/1202072743790688/f

**Comment by darrylweaver** [comment]
https://github.com/weaveworks/cx-presales/tree/main/darryldemo/kind-wge-demo/platform/monitoring - this is the kustomize config for it.

**Comment by darrylweaver** [comment]
I decided to do this with the existing Prometheus profile as I figure we are always going to want the flux dashboards included in all deployments.
The PR for it is in profiles-catalog for review and full testing before we put it on this repo ready for demos.

**Comment by darrylweaver** [comment]
https://github.com/weaveworks/profiles-catalog/pull/184

**Comment by darrylweaver** [comment]
Added the PR here for approval to deploy the flux dashboards.
https://github.com/weaveworks/weave-gitops-profile-examples/pull/79
